print("START")

if type(package.loaded['testing']) ~= 'table' then
    package.loaded['testing'] = nil
end

if not package.loaded['testing'] then
    print("Loading pkg: testing")

    t = {}
    package.loaded['testing'] = t
    print(package.loaded['testing'])
    print(type(package.loaded['testing']))

    t._VERSION = '1.0.0'
else
    print(package.loaded['testing'])
    print(type(package.loaded['testing']))
end
print("END")
